services:
  api:
    image: api
    ports:
      - "8080:80"
    build:
      context: .
      # target: runner
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
